name: Run repo scraper

on:
  #push:
  #  branches: [main]
  #schedule:
  #  - cron: "0 0 * * *"  # Run at the end of every day
  workflow_dispatch: {}  # manual executions

jobs:
  scrape:
    name: Run repo scraper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/repo_scraper/requirements.txt
          pip list

      - name: Run repo scraper
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python tools/repo_scraper/repo_scraper.py
